import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/components/provider/NextAuthProvider";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import ClientCall from "@/components/clientCall";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: '--font-inter', 
  subsets: ['latin'],      
  weight: ['400', '500', '700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} antialiased`}
      >
        <NextAuthProvider>
          <ClientCall/>
           <ReactQueryProvider>
            {children}
           </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
